In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'col1' : [1,2,3,4,5],
              'col2' : [45,56,67,34,34],
              'col3' : "sudhanshu kumar krish ineuron one".split()
    })

In [3]:
 "sudhanshu kumar krish ineuron one".split()  #based on space it splits

['sudhanshu', 'kumar', 'krish', 'ineuron', 'one']

In [4]:
df

col1  col2       col3
0     1    45  sudhanshu
1     2    56      kumar
2     3    67      krish
3     4    34    ineuron
4     5    34        one

In [5]:
df['col4'] = 1

In [6]:
df

col1  col2       col3  col4
0     1    45  sudhanshu     1
1     2    56      kumar     1
2     3    67      krish     1
3     4    34    ineuron     1
4     5    34        one     1

In [7]:
#Inorder to get square values of of col1 in col4

In [8]:
df['col4'] = df['col1']**2

In [9]:
df

col1  col2       col3  col4
0     1    45  sudhanshu     1
1     2    56      kumar     4
2     3    67      krish     9
3     4    34    ineuron    16
4     5    34        one    25

In [10]:
#OR

In [11]:
#Create col5 where it will hold the 1st character of col3

In [12]:
df['col5'] = df['col3'].str[0]

In [13]:
df

col1  col2       col3  col4 col5
0     1    45  sudhanshu     1    s
1     2    56      kumar     4    k
2     3    67      krish     9    k
3     4    34    ineuron    16    i
4     5    34        one    25    o

In [14]:
#Create col6 where it should be a deriation of col5, if s, keep s and if not s, keep z

In [15]:
#Lambda function 

In [16]:
def test(a):
    return a**2

In [17]:
df['col_4'] = df['col1'].apply(test)

In [18]:
df

col1  col2       col3  col4 col5  col_4
0     1    45  sudhanshu     1    s      1
1     2    56      kumar     4    k      4
2     3    67      krish     9    k      9
3     4    34    ineuron    16    i     16
4     5    34        one    25    o     25

In [19]:
def test1(a):
    if a == 's':
        return 's'
    else:
        return 'z'

In [20]:
df['col6'] = df['col5'].apply(test1)

In [21]:
df

col1  col2       col3  col4 col5  col_4 col6
0     1    45  sudhanshu     1    s      1    s
1     2    56      kumar     4    k      4    z
2     3    67      krish     9    k      9    z
3     4    34    ineuron    16    i     16    z
4     5    34        one    25    o     25    z

In [22]:
df['col6_6'] = df['col5'].apply(lambda a: 's' if a == 's' else 'z')

In [23]:
df

col1  col2       col3  col4 col5  col_4 col6 col6_6
0     1    45  sudhanshu     1    s      1    s      s
1     2    56      kumar     4    k      4    z      z
2     3    67      krish     9    k      9    z      z
3     4    34    ineuron    16    i     16    z      z
4     5    34        one    25    o     25    z      z

In [24]:
#Create a new column where it will hold length of the string

In [25]:
df['col7'] = df['col3'].apply(len)

In [26]:
df

col1  col2       col3  col4 col5  col_4 col6 col6_6  col7
0     1    45  sudhanshu     1    s      1    s      s     9
1     2    56      kumar     4    k      4    z      z     5
2     3    67      krish     9    k      9    z      z     5
3     4    34    ineuron    16    i     16    z      z     7
4     5    34        one    25    o     25    z      z     3

In [27]:
import math

In [28]:
df["col8"] = df['col2'].apply(math.log)

In [29]:
df

col1  col2       col3  col4 col5  col_4 col6 col6_6  col7      col8
0     1    45  sudhanshu     1    s      1    s      s     9  3.806662
1     2    56      kumar     4    k      4    z      z     5  4.025352
2     3    67      krish     9    k      9    z      z     5  4.204693
3     4    34    ineuron    16    i     16    z      z     7  3.526361
4     5    34        one    25    o     25    z      z     3  3.526361

In [30]:
import numpy as np

In [31]:
l = ["sudh", 1,2,3,4,5]

In [32]:
type(l)

list

In [33]:
np.array(l)

array(['sudh', '1', '2', '3', '4', '5'], dtype='<U11')

In [34]:
type(np.array(l))

numpy.ndarray

In [35]:
a1 = np.array([3,4,5,6,3.0])

In [36]:
a = np.array([[1,2], [3,4]])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
a[1]

array([3, 4])

In [39]:
a[1][1]

4

In [40]:
a1

array([3., 4., 5., 6., 3.])

In [41]:
a1[1]

4.0

In [42]:
np.array([1,2,3,4], ndmin = 2)  #ndmin creates 

array([[1, 2, 3, 4]])

In [43]:
np.array([1,2,3,4], ndmin = 3)

array([[[1, 2, 3, 4]]])

In [44]:
a2 = np.array([1,2,3,4], ndmin = 4)

In [45]:
a2[0][0][0][0]

1

In [46]:
a2[0][0][0][1]

2

In [47]:
a2[0][0][0][2]

3

In [48]:
a2[0][0][0][3]

4

In [49]:
a

array([[1, 2],
       [3, 4]])

In [50]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [51]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [52]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [53]:
a = [1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [54]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [55]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [56]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [57]:
#Matrix is derived from array, child class of an array

In [58]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [59]:
np.fromfunction(lambda i, j : i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [60]:
  0   1   2   3   
0 T   F   F   F
1 F   T   F   F
2 F   F   T   F
3 F   F   F   T


SyntaxError: invalid syntax (<ipython-input-60-ab64ce555068>, line 1)

In [61]:
np.fromfunction(lambda i, j : i*j, (4,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [62]:
np.mat(np.fromfunction(lambda i, j : i*j, (4,4), dtype = int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [63]:
np.mat(np.fromfunction(lambda i, j, z , i*j*z , (3,3,2), dtype = int))

SyntaxError: invalid syntax (<ipython-input-63-3d3ee1cf271d>, line 1)

In [64]:
np.fromfunction(lambda i, j, z: i*j*z , (3,3,2), dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [65]:
#In above (3,3,2): we are looking for 3 matrixes with dimensions 3*2
       # z axis, x axis, y axis
    
#z axis tells the depth 

In [68]:
np.fromfunction(lambda i, j, z: i*j*z , (4,3,2), dtype = int)  #3D

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [ ]:
#We are looking for 4 matrixes of dimension 3x2

In [70]:
np.fromfunction(lambda i, j, z, p: i*j*z*p , (4,3,3,2), dtype = int) #4D

array([[[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0],
         [ 0,  0]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  1],
         [ 0,  2]],

        [[ 0,  0],
         [ 0,  2],
         [ 0,  4]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  2],
         [ 0,  4]],

        [[ 0,  0],
         [ 0,  4],
         [ 0,  8]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  3],
         [ 0,  6]],

        [[ 0,  0],
         [ 0,  6],
         [ 0, 12]]]])

In [73]:
a = np.fromfunction(lambda i, j, z: i*j*z , (4,3,2), dtype = int)

In [74]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [75]:
a.ndim

3

In [76]:
a.size

24

In [77]:
a.shape

(4, 3, 2)

In [79]:
a.dtype

dtype('int32')

In [81]:
#Array "a" into a dataframe

In [82]:
pd.DataFrame(a)   #dataframe is a 2D matrix but here we have 3D matrix

#So we need reshaping

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [83]:
a = np.fromfunction(lambda i, j: i*j , (4,3), dtype = int)

In [84]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [85]:
a = np.fromfunction(lambda i, j: i*j , (400,300), dtype = int)

In [86]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9    ...     290  \
0      0    0    0     0     0     0     0     0     0     0  ...       0   
1      0    1    2     3     4     5     6     7     8     9  ...     290   
2      0    2    4     6     8    10    12    14    16    18  ...     580   
3      0    3    6     9    12    15    18    21    24    27  ...     870   
4      0    4    8    12    16    20    24    28    32    36  ...    1160   
..   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...     ...   
395    0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  114550   
396    0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  114840   
397    0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  115130   
398    0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  115420   
399    0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  115710   

        291     292     293     294     295     296     297     298     299  
0         0       0       0       0       0       0       0       0       0  
1       291     292     293     294     295     296     297     298     299  
2       582     584     586     588     590     592     594     596     598  
3       873     876     879     882     885     888     891     894     897  
4      1164    1168    1172    1176    1180    1184    1188    1192    1196  
..      ...     ...     ...     ...     ...     ...     ...     ...     ...  
395  114945  115340  115735  116130  116525  116920  117315  117710  118105  
396  115236  115632  116028  116424  116820  117216  117612  118008  118404  
397  115527  115924  116321  116718  117115  117512  117909  118306  118703  
398  115818  116216  116614  117012  117410  117808  118206  118604  119002  
399  116109  116508  116907  117306  117705  118104  118503  118902  119301  

[400 rows x 300 columns]

In [87]:
np.random.rand(100,4)

array([[0.75813824, 0.31407653, 0.17278532, 0.39043539],
       [0.55972377, 0.07606229, 0.65443286, 0.57475029],
       [0.53689159, 0.87675327, 0.1155994 , 0.22949859],
       [0.8232904 , 0.45339716, 0.23899828, 0.44238959],
       [0.45543558, 0.56823291, 0.64630514, 0.05841331],
       [0.22598098, 0.79184639, 0.96282692, 0.46381365],
       [0.00517945, 0.89472842, 0.74150302, 0.93804192],
       [0.18204879, 0.37231543, 0.99686   , 0.95357516],
       [0.99420503, 0.26955104, 0.68504096, 0.17202685],
       [0.44741836, 0.38463123, 0.32614851, 0.77540863],
       [0.73897743, 0.97607977, 0.06055208, 0.18441938],
       [0.55304134, 0.87243734, 0.73955361, 0.27065147],
       [0.97280777, 0.73422898, 0.64519984, 0.23591205],
       [0.9793555 , 0.43946165, 0.77706305, 0.94265117],
       [0.63541007, 0.32524708, 0.1923361 , 0.32579261],
       [0.68842197, 0.47244107, 0.32128222, 0.31052554],
       [0.07103001, 0.79726952, 0.78855094, 0.66107867],
       [0.97956606, 0.09410354,

In [93]:
np.random.randint(4,50)

29

In [97]:
pd.DataFrame(np.random.randn(4,5)) #randn gives random number with a normal distribution

#Avg of these numbers is going to be zero and std dev= 1

0         1         2         3         4
0 -0.446003  0.218803 -1.184812  0.783288 -1.413809
1  1.224295 -2.431403  1.023498  0.245618  0.233117
2 -0.220658 -1.815442 -0.534282  0.010728  1.048044
3  0.732889  1.270898  2.752111  0.873981 -1.439347

In [98]:
#To change dimension of the dataset

TypeError: reshape() takes exactly 1 argument (0 given)

In [100]:
a = np.fromfunction(lambda i, j, z: i*j*z , (4,3,2), dtype = int)

In [101]:
a.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [105]:
pd.DataFrame(a.reshape(8,3))  #(row, element)

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [107]:
a.reshape(4,2,1,3,1,1)

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [110]:
a.reshape(4,-1)  #-1 or any negative number represents the default number: 4xn = 24, where n = 6

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [113]:
a.reshape(4,-33284377)  #any negative number

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [114]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [116]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [117]:
#Function in numpy equivalent to range function,
#tho normal range can take integer as step size
#But numpy range can

In [122]:
a1 = np.arange(4.2,10.5,.2)

In [123]:
a1

array([ 4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,
        6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,
        8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [124]:
a1[1:4]

array([4.4, 4.6, 4.8])

In [125]:
arr = np.random.rand(4,5)

In [126]:
arr

array([[0.53534024, 0.24263352, 0.17615918, 0.36193464, 0.24061036],
       [0.92644016, 0.06650038, 0.42282368, 0.28934764, 0.54907701],
       [0.77448735, 0.07592218, 0.30079043, 0.68314029, 0.44270546],
       [0.59296037, 0.25179758, 0.04431801, 0.77743437, 0.02540319]])

In [127]:
arr > .5

array([[ True, False, False, False, False],
       [ True, False, False, False,  True],
       [ True, False, False,  True, False],
       [ True, False, False,  True, False]])

In [130]:
arr  #Give the 2 middle numbers (Row 1,2 and column 2)

array([[0.53534024, 0.24263352, 0.17615918, 0.36193464, 0.24061036],
       [0.92644016, 0.06650038, 0.42282368, 0.28934764, 0.54907701],
       [0.77448735, 0.07592218, 0.30079043, 0.68314029, 0.44270546],
       [0.59296037, 0.25179758, 0.04431801, 0.77743437, 0.02540319]])

In [132]:
arr[[1,2] , [2]]    #(Row 1,2 and column 2)

array([0.42282368, 0.30079043])

In [133]:
arr = np.random.rand(8,5)

In [134]:
arr[1:8 , 0:3]

array([[0.89771329, 0.77314859, 0.24787823],
       [0.72999058, 0.82868074, 0.18836108],
       [0.54839718, 0.72917705, 0.8149096 ],
       [0.96701407, 0.11086149, 0.96097924],
       [0.1932596 , 0.37054819, 0.25396826],
       [0.13079633, 0.24122192, 0.56847183],
       [0.03596555, 0.23243982, 0.82110193]])

In [137]:
a2 = arr[1:8 , [0,1,2]]

In [138]:
a2

array([[0.89771329, 0.77314859, 0.24787823],
       [0.72999058, 0.82868074, 0.18836108],
       [0.54839718, 0.72917705, 0.8149096 ],
       [0.96701407, 0.11086149, 0.96097924],
       [0.1932596 , 0.37054819, 0.25396826],
       [0.13079633, 0.24122192, 0.56847183],
       [0.03596555, 0.23243982, 0.82110193]])

In [141]:
a2[0][0] = 100  #(Row 0, COLUMN 0) Reassignment operation

In [142]:
a2

array([[1.00000000e+02, 7.73148589e-01, 2.47878228e-01],
       [7.29990579e-01, 8.28680741e-01, 1.88361085e-01],
       [5.48397183e-01, 7.29177054e-01, 8.14909601e-01],
       [9.67014073e-01, 1.10861491e-01, 9.60979242e-01],
       [1.93259602e-01, 3.70548191e-01, 2.53968263e-01],
       [1.30796328e-01, 2.41221915e-01, 5.68471835e-01],
       [3.59655526e-02, 2.32439818e-01, 8.21101926e-01]])

In [146]:
a = np.array([[1,2], [3,4]])
b = np.array([[2,3], [4,5]])

In [147]:
a

array([[1, 2],
       [3, 4]])

In [148]:
b

array([[2, 3],
       [4, 5]])

In [150]:
a*b #No Matrix multiplication, only index wise multiplication

array([[ 2,  6],
       [12, 20]])

In [153]:
m = a@b #Matrix multiplication

In [154]:
m

array([[10, 13],
       [22, 29]])

In [155]:
m/0

<ipython-input-155-be1849f03ef3>:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])